# render.yaml - Create this in your project root
services:
  - type: web
    name: ai-chatbot
    env: docker
    dockerfilePath: ./Dockerfile
    
    # Add build arguments section
    dockerBuildArgs:
      VITE_SUPABASE_URL: https://nhmpwzwyyhymglgcfmqh.supabase.co
      VITE_SUPABASE_ANON_KEY: ey1xtMds8ZlX0FUsm2z...
      VITE_API_URL: https://ai-coach-speechs.onrender.com
      VITE_TTS_ENGINE: gcloud
    
    envVars:
      # Backend runtime variables
      - key: PORT
        value: 3000
      - key: GEMINI_API_URL
        value: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
      - key: GEMINI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: ELEVENLABS_VOICE_ID
        value: 21m00Tcm4TlvDq8ikWAM
      - key: GCLOUD_TTS_VOICE_NAME
        value: en-US-Wavenet-D
      - key: GCLOUD_TTS_AUDIO_ENCODING
        value: MP3
      - key: GCLOUD_TTS_SAMPLE_RATE_HERTZ
        value: 16000
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false  # This should be sync: false, not value: false